// Contract ABIs - these are imported from compiled artifacts
// After deployment, update these with actual ABIs from build/contracts/*.json

export const CONTRACT_ABIS = {
  BondToken: [
    {
      inputs: [
        { name: "name_", type: "string" },
        { name: "symbol_", type: "string" },
        { name: "description_", type: "string" },
        { name: "yield_", type: "uint256" },
        { name: "maturity_", type: "uint256" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }],
      name: "mint",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "amount", type: "uint256" }],
      name: "burnBonds",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "newYield", type: "uint256" }],
      name: "updateYield",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "hasMatured",
      outputs: [{ type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "timeToMaturity",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { name: "principal", type: "uint256" },
        { name: "startTime", type: "uint256" },
        { name: "endTime", type: "uint256" },
      ],
      name: "calculateYield",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getBondMetadata",
      outputs: [
        { name: "name", type: "string" },
        { name: "symbol", type: "string" },
        { name: "description", type: "string" },
        { name: "yield", type: "uint256" },
        { name: "maturity", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ name: "account", type: "address" }],
      name: "balanceOf",
      outputs: [{ name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "to", type: "address" },
        { indexed: false, name: "amount", type: "uint256" },
      ],
      name: "BondsMinted",
      type: "event",
    },
  ],

  ProjectRegistry: [
    {
      inputs: [
        { name: "name_", type: "string" },
        { name: "description_", type: "string" },
        { name: "location_", type: "string" },
        { name: "targetAmount_", type: "uint256" },
        { name: "yieldPercentage_", type: "uint256" },
        { name: "duration_", type: "uint256" },
        { name: "ipfsHash_", type: "string" },
        { name: "bondTokenAddress_", type: "address" },
        { name: "insuranceRequired_", type: "bool" },
      ],
      name: "createProject",
      outputs: [{ type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { name: "projectId_", type: "uint256" },
        { name: "title_", type: "string" },
        { name: "description_", type: "string" },
        { name: "targetDate_", type: "uint256" },
        { name: "fundAmount_", type: "uint256" },
      ],
      name: "addMilestone",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "projectId_", type: "uint256" }],
      name: "getProject",
      outputs: [
        {
          components: [
            { name: "id", type: "uint256" },
            { name: "name", type: "string" },
            { name: "description", type: "string" },
            { name: "municipality", type: "address" },
            { name: "location", type: "string" },
            { name: "targetAmount", type: "uint256" },
            { name: "raisedAmount", type: "uint256" },
            { name: "yieldPercentage", type: "uint256" },
            { name: "duration", type: "uint256" },
            { name: "createDate", type: "uint256" },
            { name: "status", type: "uint8" },
            { name: "ipfsHash", type: "string" },
            { name: "bondTokenAddress", type: "address" },
            { name: "totalMilestones", type: "uint256" },
            { name: "insuranceRequired", type: "bool" },
          ],
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ name: "projectId_", type: "uint256" }],
      name: "getProjectMilestones",
      outputs: [
        {
          components: [
            { name: "title", type: "string" },
            { name: "description", type: "string" },
            { name: "targetDate", type: "uint256" },
            { name: "fundAmount", type: "uint256" },
            { name: "completed", type: "bool" },
            { name: "approved", type: "bool" },
            { name: "completionDate", type: "uint256" },
          ],
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getTotalProjects",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
  ],

  MilestoneEscrow: [
    {
      inputs: [{ name: "projectId_", type: "uint256" }, { name: "amount_", type: "uint256" }],
      name: "depositFunds",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "projectId_", type: "uint256" }],
      name: "getProjectEscrowBalance",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ name: "projectId_", type: "uint256" }, { name: "investor_", type: "address" }],
      name: "getInvestorHoldings",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
  ],

  GovernanceDAO: [
    {
      inputs: [
        { name: "projectId_", type: "uint256" },
        { name: "milestoneIndex_", type: "uint256" },
        { name: "title_", type: "string" },
        { name: "description_", type: "string" },
        { name: "releaseTarget_", type: "address" },
        { name: "releaseAmount_", type: "uint256" },
      ],
      name: "createProposal",
      outputs: [{ type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "proposalId_", type: "uint256" }, { name: "voteType_", type: "uint8" }],
      name: "vote",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "proposalId_", type: "uint256" }],
      name: "getProposal",
      outputs: [
        {
          components: [
            { name: "id", type: "uint256" },
            { name: "projectId", type: "uint256" },
            { name: "milestoneIndex", type: "uint256" },
            { name: "title", type: "string" },
            { name: "description", type: "string" },
            { name: "proposer", type: "address" },
            { name: "createdAt", type: "uint256" },
            { name: "startTime", type: "uint256" },
            { name: "endTime", type: "uint256" },
            { name: "forVotes", type: "uint256" },
            { name: "againstVotes", type: "uint256" },
            { name: "abstainVotes", type: "uint256" },
            { name: "status", type: "uint8" },
            { name: "releaseTarget", type: "address" },
            { name: "releaseAmount", type: "uint256" },
            { name: "executed", type: "bool" },
          ],
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
  ],

  RepaymentManager: [
    {
      inputs: [{ name: "projectId_", type: "uint256" }],
      name: "recordPayment",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ name: "projectId_", type: "uint256" }],
      name: "getRepaymentSchedule",
      outputs: [
        {
          components: [
            { name: "projectId", type: "uint256" },
            { name: "totalPrincipal", type: "uint256" },
            { name: "totalInterest", type: "uint256" },
            { name: "startDate", type: "uint256" },
            { name: "endDate", type: "uint256" },
            { name: "paymentFrequency", type: "uint256" },
            { name: "frequencyCount", type: "uint256" },
            { name: "amountPerPayment", type: "uint256" },
            { name: "paymentsReceived", type: "uint256" },
            { name: "lastPaymentDate", type: "uint256" },
            { name: "defaulted", type: "bool" },
            { name: "status", type: "string" },
          ],
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
  ],

  RevenueEngine: [
    {
      inputs: [{ name: "projectId_", type: "uint256" }, { name: "amount_", type: "uint256" }],
      name: "collectIssuanceFee",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "getTreasuryBalance",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ name: "amount_", type: "uint256" }, { name: "feeType_", type: "string" }],
      name: "calculateFee",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
  ],

  InsurancePool: [
    {
      inputs: [{ name: "projectId_", type: "uint256" }, { name: "coverageAmount_", type: "uint256" }],
      name: "enableCoverage",
      outputs: [{ type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "getPoolBalance",
      outputs: [{ type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
  ],
};
